services:
  mmdetection:
    image: mmdetection  
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PYTORCH: "2.7.0"
        CUDA: "12.8"
        CUDNN: "9"
    container_name: mmdetection
    runtime: nvidia
    shm_size: 8g
    tty: true
    stdin_open: true
    volumes:
      - /home/andrian/envs/mmdet/mmdetection/data/coco:/mmdetection/data/coco
      - ./configs:/mmdetection/configs  # Optional: for custom configs
      - ./work_dirs:/mmdetection/work_dirs  # Optional: to persist training outputs
    environment:
      - TORCH_CUDA_ARCH_LIST=6.0 6.1 7.0 7.5 8.0 8.6 9.0+PTX
      - TORCH_NVCC_FLAGS=-Xfatbin -compress-all
      - FORCE_CUDA=1
    working_dir: /mmdetection