services:
  mmdetection:
    image: mmdet_mmpose
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PYTORCH: "2.7.0"
        CUDA: "12.8"
        CUDNN: "9"
    container_name: mmdet_mmpose
    shm_size: 8g
    tty: true
    stdin_open: true
    volumes:
      - /home/andrian/envs/mmdet/mmdetection/data/coco:/mmdetection/data/coco
      - ./configs:/mmdetection/configs
      - ./work_dirs:/mmdetection/work_dirs
      - ./mmpose:/mmpose 
      - /home/andrian/envs/mmdet/mmpose/data:/mmpose/data  # Mount MMPose keypoint data
    environment:
      - TORCH_CUDA_ARCH_LIST=6.0 6.1 7.0 7.5 8.0 8.6 9.0+PTX
      - TORCH_NVCC_FLAGS=-Xfatbin -compress-all
      - FORCE_CUDA=1
    working_dir: /mmdetection
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
